name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"
  
  defaults:
    run:
      shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove previous .west config if it exists
        run: |
          if [ -d ".west" ]; then
            rm -rf .west
          fi

      - name: Run ZMK build workflow
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
