name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git cmake ninja-build gperf ccache dfu-util device-tree-compiler wget python3-pip python3-setuptools python3-wheel xz-utils file make gcc g++ unzip
          pip install west
          west init -l zmk
          west update
          west zephyr-export
          pip install -r zmk/zephyr/scripts/requirements.txt

      - name: Build firmware (left)
        run: |
          west build -s zmk/app -d build/left -b eyelash_corne_left -- -DSHIELD=nice_view -DZMK_CONFIG=config

      - name: Upload left firmware
        uses: actions/upload-artifact@v4
        with:
          name: zmk-left
          path: build/left/zephyr/zmk.uf2
